<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-29 at 14:32:54.
 */
class VoorbeeldTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Voorbeeld
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Voorbeeld;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Voorbeeld::add
     * @depen ds testGet
     */
    public function testAdd() {
        $this->object->add(42);
        $this->assertEquals(42, $this->object->get(0));
        $this->object->add(421);
        $this->assertEquals(421, $this->object->get(1));
    }

    /**
     * see https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html
     * @expectedException Exception
     * @covers Voorbeeld::get
     */
    public function testGetException() {
        $x = $this->object->get(0);
    }

    /**
     * constructor zou de class (instance) moeten retourneren. 
     * is dat zo?
     */
    public function testConstructorReturnObject() {
        $this->assertEquals("Voorbeeld", get_class($this->object));
    }

    /**
     * Add zou de class (instance) moeten retourneren.
     * Is dat zo?
     */
    public function testAddReturnObject() {
        $this->assertEquals("Voorbeeld", get_class($this->object->add("")));
    }

    /**
     * @depends testConstructorReturnObject
     */
    public function testChain() {
        $t = "chainVoorbeeld";
        $x = (new Voorbeeld())->add($t);
        $this->assertEquals($t, $x->get(0), "chain voorbeeld");
    }

    /**
     * @covers Voorbeeld::get
     * @depends testGetException
     */
    public function testGet() {
        $this->object->a[0] = 1;    // dirty, chicken and egg issue
        $this->assertEquals(1, $this->object->get(0));
    }

    /**
     * @covers Voorbeeld::waarde
     * @todo   Implement testWaarde().
     */
    public function testWaarde() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
